//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : PSDE
//  @ File Name : CGeomCollection.h
//  @ Date : 2010/12/20
//  @ Author : 
//
//


#if !defined(_CGEOMCOLLECTION_H)
#define _CGEOMCOLLECTION_H

#include "CGeometry.h"

namespace Geometry {

class CGeomCollection: public CGeometry {
public:
	CGeomCollection();
	CGeomCollection(const CGeomCollection & coll);
	CGeomCollection(vector<CGeometry *> * geoms);
	~CGeomCollection();
	CGeometry* clone() const;
public:
	double getArea() const;
	double getLength() const;
	size_t getNumPoints() const;
	size_t getNumGeometries() const;
	CCoVecSequence *getCoordinates() const;

	bool equalExact(CGeometry* geom, double eps) const;
	const CGeometry* getGeometryAt(size_t pos) const;
	CRectangle getBoundingRect() const;
	string getGeometryType() const;
	COpenGISType::OPENGIS_TYPE getOGISType() const;
	bool isSimple() const;
	bool isEmpty() const;
	bool isValid() const;
protected:
	vector<CGeometry *> * mGeoms;
};
}

#endif  //_CGEOMCOLLECTION_H
