//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : PSDE
//  @ File Name : CLinearRing.h
//  @ Date : 2010/12/20
//  @ Author : 
//
//


#if !defined(_CLINEARRING_H)
#define _CLINEARRING_H

#include "CLineString.h"

namespace Geometry {
class CLinearRing: public CLineString {
public:
	CLinearRing();
	CLinearRing(const CLinearRing & ln);
	CLinearRing(const CCoVecSequence & seq);
	~CLinearRing();
	CGeometry* clone() const;
	string getGeometryType() const;
	COpenGISType::OPENGIS_TYPE getOGISType() const;
private:

	void validate();
};
}

#endif  //_CLINEARRING_H
