//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : PSDE
//  @ File Name : CMultiPolygon.h
//  @ Date : 2010/12/20
//  @ Author : 
//
//


#if !defined(_CMULTIPOLYGON_H)
#define _CMULTIPOLYGON_H

#include "CGeomCollection.h"
namespace Geometry {
class CMultiPolygon: public CGeomCollection {
public:
	CMultiPolygon();
	CMultiPolygon(const CMultiPolygon & mp);
	CMultiPolygon(vector<CGeometry *> * geos);
	~CMultiPolygon();
	CGeometry* clone() const;
public:
	bool equalExact(CGeometry* geom, double eps) const;
	string getGeometryType() const;
	COpenGISType::OPENGIS_TYPE getOGISType() const;
};
}

#endif  //_CMULTIPOLYGON_H
