//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : PSDE
//  @ File Name : CMultiLineString.h
//  @ Date : 2010/12/20
//  @ Author : 
//
//


#if !defined(_CMULTILINESTRING_H)
#define _CMULTILINESTRING_H

#include "CGeomCollection.h"

namespace Geometry {
class CMultiLineString: public CGeomCollection {
public:
	CMultiLineString();
	CMultiLineString(const CMultiLineString & ml);
	CMultiLineString(vector<CGeometry *> * geos);
	~CMultiLineString();
	CGeometry* clone() const;
public:
	bool equalExact(CGeometry* geom, double eps) const;
	string getGeometryType() const;
	COpenGISType::OPENGIS_TYPE getOGISType() const;
};
}

#endif  //_CMULTILINESTRING_H
