//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : PSDE
//  @ File Name : CMultiPolygon.cpp
//  @ Date : 2010/12/20
//  @ Author : 
//
//


#include "CMultiPolygon.h"

namespace Geometry {
CMultiPolygon::CMultiPolygon() :
	CGeomCollection() {

}

CMultiPolygon::CMultiPolygon(const CMultiPolygon & ml) :
	CGeomCollection(ml) {

}

CMultiPolygon::CMultiPolygon(vector<CGeometry *> * newLineString) :
	CGeomCollection(newLineString) {

}

CMultiPolygon::~CMultiPolygon() {

}


CGeometry* CMultiPolygon::clone() const {
	return new CMultiPolygon(*this);
}

bool CMultiPolygon::equalExact(CGeometry* geom, double eps)const {
	if (!isEquivalentClass(geom))
		return false;
	return CGeomCollection::equalExact(geom, eps);
}


string CMultiPolygon::getGeometryType()const {
	return "CMultiPolygon";
}
COpenGISType::OPENGIS_TYPE CMultiPolygon::getOGISType()const {
	return COpenGISType::OGIS_MULTIPOLYGON;
}
}
