//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : PSDE
//  @ File Name : CMultiLineString.cpp
//  @ Date : 2010/12/20
//  @ Author : 
//
//


#include "CMultiLineString.h"

namespace Geometry {
CMultiLineString::CMultiLineString() :
	CGeomCollection() {

}

CMultiLineString::CMultiLineString(const CMultiLineString & ml) :
	CGeomCollection(ml) {

}

CMultiLineString::CMultiLineString(vector<CGeometry *> * newLineString) :
	CGeomCollection(newLineString) {

}

CMultiLineString::~CMultiLineString() {

}

CGeometry* CMultiLineString::clone() const {
	return new CMultiLineString(*this);
}

bool CMultiLineString::equalExact(CGeometry* geom, double eps)const {
	if (!isEquivalentClass(geom))
		return false;
	return CGeomCollection::equalExact(geom, eps);
}


string CMultiLineString::getGeometryType()const {
	return "CMultiLineString";
}
COpenGISType::OPENGIS_TYPE CMultiLineString::getOGISType()const {
	return COpenGISType::OGIS_MULTILINESTRING;
}
}
