//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : PSDE
//  @ File Name : CMultiPoint.h
//  @ Date : 2010/12/20
//  @ Author : 
//
//


#if !defined(_CMULTIPOINT_H)
#define _CMULTIPOINT_H

#include "CGeomCollection.h"

namespace Geometry {
class CMultiPoint: public CGeomCollection {
public:
	CMultiPoint();
	CMultiPoint(const CMultiPoint & mp);
	CMultiPoint(vector<CGeometry *> * geos);
	~CMultiPoint();
	CGeometry* clone() const;
public:

	bool equalExact(CGeometry* geom, double eps) const;
	string getGeometryType() const;
	COpenGISType::OPENGIS_TYPE getOGISType() const;

	CCoordinate getCoordinateAt(size_t pos) const;
};
}

#endif  //_CMULTIPOINT_H
