//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : PSDE
//  @ File Name : CRectangle.h
//  @ Date : 2010/12/20
//  @ Author : 
//
//


#if !defined(_CRECTANGLE_H)
#define _CRECTANGLE_H
#include "CCoordinate.h"
#include <algorithm>
#include <string>
using namespace std;
namespace Geometry {

}

namespace Geometry {
class CRectangle {
public:
	CRectangle();
	CRectangle(double x1, double y1, double x2, double y2);
	CRectangle(CCoordinate & p1, CCoordinate & p2);
	double getMinX();
	double getMinY();
	double getMaxX();
	double getMaxY();
	double getArea();
	void getBoundingBox(double minp[2], double maxp[2]);
	bool isEmpty();
	string AsBox3d();
public:
	double minx;
	double miny;
	double maxx;
	double maxy;
};
}

#endif  //_CRECTANGLE_H
